// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MutatePluginPayload struct {
	Successful bool             `json:"successful"`
	Plugin     *NevermorePlugin `json:"plugin"`
}

type NevermorePluginChannel struct {
	Name     string                    `json:"name"`
	Plugin   *NevermorePlugin          `json:"plugin"`
	Versions []*NevermorePluginVersion `json:"versions"`
}

type NevermorePluginPage struct {
	PageNum int                `json:"pageNum"`
	HasNext bool               `json:"hasNext"`
	Plugins []*NevermorePlugin `json:"plugins"`
}

type NevermorePluginVersion struct {
	ID              string                  `json:"id"`
	Plugin          *NevermorePlugin        `json:"plugin"`
	Channel         *NevermorePluginChannel `json:"channel"`
	ShortIdentifier string                  `json:"shortIdentifier"`
	FullIdentifier  string                  `json:"fullIdentifier"`
	Readme          *string                 `json:"readme"`
	DownloadURL     string                  `json:"downloadUrl"`
}

type UploadPayload struct {
	URL string `json:"url"`
}
