name: Deploy to poesitory.edgarallanohms.com
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Start Deployment
      uses: wshihadeh/docker-deployment-action@v1
      env:
        GITHUB_CLIENT_ID: ${{ secrets.I_GITHUB_CLIENT_ID }}
        GITHUB_CLIENT_SECRET: ${{ secrets.I_GITHUB_CLIENT_SECRET }}
        GITLAB_CLIENT_ID: ${{ secrets.GITLAB_CLIENT_ID }}
        GITLAB_CLIENT_SECRET: ${{ secrets.GITLAB_CLIENT_SECRET }}
        POESITORY_CA_EMAIL: ${{ secrets.POESITORY_CA_EMAIL }}
        POESITORY_SECRET: ${{ secrets.POESITORY_SECRET }}
        POESITORY_BASE_URI: "poesitory.edgarallanohms.com"
        POESITORY_CDN_URI: "cdn.poesitory.edgarallanohms.com"
        POESITORY_CERTRESOLVER: "cre"
      with:
        remote_docker_host: root@poesitory.edgarallanohms.com
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: /root/my-deployment
        stack_file_name: docker-compose.yaml
        keep_files: 5
        args: up -d --build
        docker_prune: 'false'
        pull_images_first: 'false'